name: Ng-schematics

# Declare default permissions as read only.
permissions: read-all

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '/packages/ng-schematics'

jobs:
  inspect-code:
    name: Inspect code
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 2
      - name: Set up Node.js
        uses: actions/setup-node@v3.5.1
        with:
          cache: npm
          node-version: latest
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Check code
        run: npm run check
      - name: Lint code
        run: npm run lint
      - name: Lint commits
        run: npm run commitlint
        if: github.event_name != 'pull_request'

  tests:
    name: Test Angular Schematics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3.5.1
        with:
          cache: npm
          node-version: latest
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run tests
        run: npm run test --workspace @puppeteer/ng-schematics

  docker-tests:
    name: Test Docker image
    runs-on: ubuntu-latest
    steps:
      - run: echo "Success"

  installation-test:
    name: Test ${{ matrix.pkg_manager }} installation on ${{ matrix.os }} (${{ matrix.node }})
    needs: installation-test-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node:
          - 14
          - 16
          - 18
        pkg_manager:
          - npm
    steps:
      - run: echo "Success"

  firefox-tests:
    name: ${{ matrix.suite }} tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        suite:
          - firefox-bidi
          - firefox-headful
          - firefox-headless
    steps:
      - run: echo "Success"

  chrome-tests:
    name: ${{ matrix.suite }} tests on ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        suite:
          - chrome-headless
          - chrome-headful
          - chrome-new-headless
          - chrome-bidi
        exclude:
          - os: windows-latest
            suite: chrome-bidi
    steps:
      - run: echo "Success"

  check-docs:
    name: Check documentation
    runs-on: ubuntu-latest
    outputs:
      needs_deploying: ${{ steps.needs_deploying.outputs.value }}
    steps:
      - run: echo "Success"
